### ISSUE TITLE
6.3.6 Erroneous vesting parameters can not be corrected

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/smartcontract#10]
![image](https://user-images.githubusercontent.com/9573561/126481007-1ca4b7e8-52d9-49d9-af5c-49cc5de92b0f.png)

**Comment by tbocek** [comment]
This would allow us to deviate from our initial vesting plan, and make vesting changeable at any time. I understand that an error cannot be fixed, but this is desired behaviour
