### ISSUE TITLE
6.3.7 Unnecessary gas costs by using public functions instead of external

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/smartcontract#11]
![image](https://user-images.githubusercontent.com/9573561/126481062-6dacfbbc-fb74-4662-af99-82d616451169.png)

**Comment by tbocek** [comment]
With the newest compiler, where calldata/memory can be defined, it does not matter in terms of gas if its external or public -> https://ethereum.stackexchange.com/a/99880
