### ISSUE TITLE
6.4.1 Adherence to the token issuance schedule requires a monthly transaction

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/smartcontract#13]
![image](https://user-images.githubusercontent.com/9573561/126481499-85b2b124-21f0-47f0-b43e-99546667855c.png)

**Comment by severinwullschleger** [comment]
call emitTokens every month vs. unpredictable transfer fees.

suggestion to close this issue

**Comment by tbocek** [comment]
True, if we miss one month, then for this month less tokens are issued. However, this will be compenstated the next year, where _totalEmitted is a lower value, so more tokens will be issued. At the end of the emit, all missing tokens will be emitted (also those due to roundings)
