### ISSUE TITLE
6.3.1 Dangerous use of unchecked {}

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/smartcontract#5]
![image](https://user-images.githubusercontent.com/9573561/126480739-fc29d1c4-1947-43da-a716-4dd023661887.png)

**Comment by tbocek** [comment]
I see the point, but I used the code from OpenZeppelin: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

I also double checked the unchecked and they are fine, besides, we would deviate more from the OpenZeppelin reference contracts.
