### ISSUE TITLE
6.3.4 TGT liveliness checks would be more robustly handled by modifiers

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/smartcontract#8]
![image](https://user-images.githubusercontent.com/9573561/126480907-6a05cf64-6fd7-48bb-81fe-16662635f6d1.png)

**Comment by severinwullschleger** [comment]
@tbocek do you want to do that?

**Comment by tbocek** [comment]
I double checked, and I would not use modifiers besides onlyOwner. I improved the comments
